#ifndef TRAINED_WEIGHTS_H
#define TRAINED_WEIGHTS_H

#include "tinyformer.h"

// Trained TinyFormer encoder weights (generated by tools/export_weights.py)

extern const int8_t W_q[TINYFORMER_D][TINYFORMER_D];
extern const int8_t W_k[TINYFORMER_D][TINYFORMER_D];
extern const int8_t W_v[TINYFORMER_D][TINYFORMER_D];
extern const int8_t W_o[TINYFORMER_D][TINYFORMER_D];

extern const int8_t W_ff1[TINYFORMER_FFN][TINYFORMER_D];
extern const int8_t W_ff2[TINYFORMER_D][TINYFORMER_FFN];

extern const int8_t b_q[TINYFORMER_D];
extern const int8_t b_k[TINYFORMER_D];
extern const int8_t b_v[TINYFORMER_D];
extern const int8_t b_o[TINYFORMER_D];

extern const int8_t b_ff1[TINYFORMER_FFN];
extern const int8_t b_ff2[TINYFORMER_D];

#endif // TRAINED_WEIGHTS_H
