#ifndef DEMO_CLASSIFIER_H
#define DEMO_CLASSIFIER_H

#include <stdint.h>

#define DEMO_NUM_CLASSES 6
#define DEMO_D 32

// These arrays are generated by training/export_and_make_fpga_demo.py.
extern const int8_t cls_W[DEMO_NUM_CLASSES][DEMO_D];
extern const int8_t cls_b[DEMO_NUM_CLASSES];

#endif // DEMO_CLASSIFIER_H

